/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transposition;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Action;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author vuszi
 */
public class CypherGUI extends javax.swing.JFrame{

    Encrypt enc;
    Decrypt dec;
    About abt;
    History hist;
    
    /**
     * Creates new form CypherGUI
     */
    public CypherGUI() {
        
        hist = new History();
        abt = new About();
        enc = new Encrypt();
        dec = new Decrypt();
        initComponents();
        
        btnGroup.add(rdbDecrypt);
        btnGroup.add(rdbEncrypt);
        
        txtMessage.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (rdbEncrypt.isSelected()){
                    txtResult.setText(enc.encrypt(enc.encrypt(enc.encrypt(txtMessage.getText()))));
                }else if (rdbDecrypt.isSelected()){
                    txtResult.setText(dec.decrypt(dec.decrypt(dec.decrypt(txtMessage.getText()))));
                }
            }
        });   
        
        
//        
//        menus
//           
        Action cutAction = new DefaultEditorKit.CutAction();
        cutAction.putValue(Action.ACCELERATOR_KEY,(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK)));
        cutAction.putValue(Action.NAME, "Cortar");
        editMenu.add(cutAction);
        
        Action copyAction = new DefaultEditorKit.CopyAction();
        copyAction.putValue(Action.ACCELERATOR_KEY,(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK)));
        copyAction.putValue(Action.NAME, "Copiar");
        editMenu.add(copyAction);

        Action pasteAction = new DefaultEditorKit.PasteAction();
        pasteAction.putValue(Action.ACCELERATOR_KEY,(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK)));
        pasteAction.putValue(Action.NAME, "Pegar ");
        editMenu.add(pasteAction);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMsj = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        rdbEncrypt = new javax.swing.JRadioButton();
        rdbDecrypt = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newSess = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAbt = new javax.swing.JMenuItem();
        manuHist = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Para encriptar o desencriptar un mensaje");

        jLabel2.setText("selecciona una de las opciones a la derecha.");

        lblMsj.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        lblMsj.setForeground(new java.awt.Color(36, 52, 102));
        lblMsj.setText("Mensaje");

        lblResult.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(36, 52, 102));
        lblResult.setText("Mensaje Encriptado");

        txtMessage.setBackground(new java.awt.Color(254, 254, 254));
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        txtResult.setBackground(new java.awt.Color(186, 184, 184));
        txtResult.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtResult.setForeground(new java.awt.Color(1, 1, 1));

        rdbEncrypt.setSelected(true);
        rdbEncrypt.setText("Encriptar");
        rdbEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEncryptActionPerformed(evt);
            }
        });

        rdbDecrypt.setText("Desencriptar");
        rdbDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDecryptActionPerformed(evt);
            }
        });

        jLabel3.setText("y comienza a escribir");

        jMenu1.setText("Archivo");

        newSess.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newSess.setText("Nueva Sesion");
        newSess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessActionPerformed(evt);
            }
        });
        jMenu1.add(newSess);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        editMenu.setText("Editar");
        jMenuBar1.add(editMenu);

        jMenu2.setText("Ayuda");

        menuAbt.setText("Acerca...");
        menuAbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbtActionPerformed(evt);
            }
        });
        jMenu2.add(menuAbt);

        manuHist.setText("Historial");
        manuHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuHistActionPerformed(evt);
            }
        });
        jMenu2.add(manuHist);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblMsj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbDecrypt)
                            .addComponent(rdbEncrypt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(txtMessage, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbEncrypt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbDecrypt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMsj, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEncryptActionPerformed
        lblMsj.setText("Mensaje");
        lblResult.setText("Mensaje Encriptado");
        hist.txtfHistory.append("\n"+txtMessage.getText());
        hist.txtfHistory.append("\n"+enc.encrypt(enc.encrypt(enc.encrypt(txtMessage.getText()))));
        txtMessage.setText("");
        txtResult.setText(enc.encrypt(enc.encrypt(enc.encrypt(txtMessage.getText()))));
        
    }//GEN-LAST:event_rdbEncryptActionPerformed

    private void rdbDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDecryptActionPerformed
        lblMsj.setText("Mensaje Encriptado");
        lblResult.setText("Mensaje");
        hist.txtfHistory.append("\n"+txtMessage.getText());
        hist.txtfHistory.append("\n"+enc.encrypt(enc.encrypt(enc.encrypt(txtMessage.getText()))));
        txtMessage.setText("");
        txtResult.setText(dec.decrypt(dec.decrypt(dec.decrypt(txtMessage.getText()))));
    }//GEN-LAST:event_rdbDecryptActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        hist.txtfHistory.append("\n"+txtMessage.getText());
        hist.txtfHistory.append("\n"+enc.encrypt(enc.encrypt(enc.encrypt(txtMessage.getText()))));
    }//GEN-LAST:event_txtMessageActionPerformed

    private void newSessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessActionPerformed
        hist.txtfHistory.append("\n"+txtMessage.getText());
        hist.txtfHistory.append("\n"+enc.encrypt(enc.encrypt(enc.encrypt(txtMessage.getText()))));
        txtMessage.setText("");
        txtResult.setText("");
    }//GEN-LAST:event_newSessActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbtActionPerformed
        abt.setVisible(true);
    }//GEN-LAST:event_menuAbtActionPerformed

    private void manuHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuHistActionPerformed
        hist.setVisible(true);
    }//GEN-LAST:event_manuHistActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CypherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CypherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CypherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CypherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CypherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JMenu editMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMsj;
    private javax.swing.JLabel lblResult;
    private javax.swing.JMenuItem manuHist;
    private javax.swing.JMenuItem menuAbt;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem newSess;
    private javax.swing.JRadioButton rdbDecrypt;
    private javax.swing.JRadioButton rdbEncrypt;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
